webtruyentranh/Controllers/NovelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using WebTruyenTranhDataAccess.Context;
using System.Diagnostics;
using WebTruyenTranhDataAccess.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using webtruyentranh.Viewmodels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using webtruyentranh.Utility;

using Microsoft.AspNetCore.Identity;

namespace webtruyentranh.Controllers
{
    public class NovelController : Controller
    {
        private readonly ComicContext _db;
        private readonly UserManager<Account> userManager;

        public NovelController(ComicContext _db, UserManager<Account> userManager)
        {
            this._db = _db;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Getnovels()
        {
            var genre = _db.Genres.ToList();

            return View(genre);
        }

        [HttpGet]
        public JsonResult RequestItems(long ge, String q, int pagination, string search)
        {
            int staticnum = pagination * 5;
            int count;
            IEnumerable<Novel> novels;
            if (ge == 0)
            {
                novels = _db.Novels.Include(n => n.Genres).Include(n => n.Likes); if (search != null) { novels = novels.Where(n => n.Title.Contains(search) || n.Genres.Any(g => g.GenreName.Contains(search))); }
                count = novels.Count();
            }
            else
            {
                novels = _db.Novels.Include(n => n.Genres).Where(n => n.Genres.Any(g => g.Id == ge)); if (search != null) { novels = novels.Where(n => n.Title.Contains(search) || n.Genres.Any(g => g.GenreName.Contains(search))); }
                count = novels.Count();
            }
            if (q.Equals("POPULAR"))
            {
                novels = novels.OrderByDescending(n => n.LikeCount);
            }
            if (q.Equals("FRESH"))
            {
                novels = novels.OrderBy(n => n.LastestUpdate);
            }

            novels = novels.Skip(staticnum - 5).Take(5).ToList();  
            var Featurednovel = _db.Novels.Include(n => n.Genres).ToList().OrderByDescending(n => n.LastestUpdate).Skip(0).Take(2).ToList();


            //ViewBag.pagination = pagination+1;
            return Json(JsonConvert.SerializeObject(new { Novels = novels, countresult = count, Featurednovel = Featurednovel }, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                Formatting = Formatting.Indented
            }));
        }

        [Authorize]
        public async Task<IActionResult> DoSubscription(long Id)
        {
            try
            {
                var account = await userManager.GetUserAsync(User);
                var any = _db.Subscriptions.Where(s => s.AccountId == account.Id).Where(s => s.NovelId == Id).SingleOrDefault();
                if (any == null)
                {
                    _db.Subscriptions.Add(new Subscription
                    {
                        AccountId = account.Id,
                        NovelId = Id,
                        ExpirationDate = DateTime.Now
                    });
                    _db.SaveChanges();
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            return Ok();
        }

        public async Task<IActionResult> UnSubscription(long Id)
        {
            try
            {
                var account = await userManager.GetUserAsync(User);
                var any = _db.Subscriptions.Where(s => s.AccountId == account.Id).Where(s => s.NovelId == Id).SingleOrDefault();
                if (any != null)
                {
                    _db.Remove(any);
                    _db.SaveChanges();
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            return Ok();
        }

        public async Task<IActionResult> Dolike(long Id)
        {
            try
            {
                var account = await userManager.GetUserAsync(User);
                var any = _db.Likes.Where(l => l.AccountId == account.Id).Where(l => l.NovelId == Id).SingleOrDefault();
                if (any == null)
                {
                    _db.Likes.Add(new Like
                    {
                        AccountId = account.Id,
                        NovelId = Id
                    });
                    _db.SaveChanges();
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            return Ok();
        }

        public async Task<IActionResult> UnLike(long Id)
        {
            try
            {
                var account = await userManager.GetUserAsync(User);
                var any = _db.Likes.Where(l => l.AccountId == account.Id).Where(l => l.NovelId == Id).SingleOrDefault();
                if (any != null)
                {
                    _db.Remove(any);
                    _db.SaveChanges();
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                return NotFound();
            }
            return Ok();
        }

        [Authorize]
        [HttpGet]
        public IActionResult CreateNovels()
        {
            var item = _db.Genres.Select(x => new SelectListItem()
            {
                Text = x.GenreName,
                Value = x.Id.ToString(),
            }).ToList();
            var gn = new UploadImage_Viewmodel()
            {
                genres = item
            };
            return View(gn);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNovelsAsync(UploadImage_Viewmodel createnovel)
        {
            if (ModelState.IsValid)

            {
                var account = await userManager.GetUserAsync(User);
                var nv = new Novel();
                nv.Title = createnovel.Title;
                nv.Description = createnovel.Description;
                nv.LikeCount = 0;
                nv.LastestUpdate = DateTime.Now;
                nv.Account = account;
                Task task1 = new Task(async () => { nv.Thumbnail = await Cloudinary_Utility.uploadavartar(createnovel.Thumbnail); });
                Task task2 = new Task(async () => { nv.BookCover = await Cloudinary_Utility.uploadavartar(createnovel.Bookcover); });
                Task task3 = new Task(async () => { nv.Banner = await Cloudinary_Utility.uploadavartar(createnovel.Banner); });

                task1.Start();
                task2.Start();
                task3.Start();
                task1.Wait();
                task2.Wait();

                nv.Slugify = Slugify.GenerateSlug(nv.Title);
                var genresIds = createnovel.genres.Where(x => x.Selected)
                                                .Select(y => y.Value);

                var genres = _db.Genres.Where(g => genresIds.Contains(g.Id.ToString())).ToList();

                try
                {
                    _db.Attach(account);
                    _db.Novels.Add(nv);
                    nv.Genres = (List<Genre>)genres;
                    _db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("save_error", "Save Error" + ex.Message);
                    return View(createnovel);
                }
                return RedirectToAction("Sumary", "Dashboard");
            }
            return View(createnovel);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> UpdateNovel(long id)
        {
            try
            {
                var novel = _db.Novels.Include(p => p.Account).Include(h => h.Genres).Where(novel => novel.Id == id).First();
                //lay tat ca the loai duoi db len
                var item = _db.Genres.Select(x => new SelectListItem()
                {
                    Text = x.GenreName,
                    Value = x.Id.ToString(),
                }
                ).ToList();

                foreach (var genredb in item) //xet tat ca the laoi duoi db
                {
                    foreach (var genre in novel.Genres) //xet tat ca the loai cua novel dc chon
                    {
                        if (genredb.Value.Equals(genre.Id.ToString())) //neu id the loai duoi db=id the loai cua novel thi tick
                        {
                            genredb.Selected = true; //hien thi da chon
                        }
                    }
                }
                var updateNovelView = new UploadImage_Viewmodel()
                {
                    Id = novel.Id,
                    Title = novel.Title,
                    Description = novel.Description,
                    genres = item,
                };
                ViewBag.recentThumbnail = novel.Thumbnail;
                ViewBag.recentBookcover = novel.BookCover;
                ViewBag.recentBanner = novel.Banner;
                return View(updateNovelView);
            }
            catch (Exception ex)
            {

webtruyentranh/Views/Novel/CreateNovels.cshtml
@model UploadImage_Viewmodel
@{
    ViewData["Title"] = "CreateNovels";
    Layout = "~/Views/Shared/_Layoutpage.cshtml";

}

<link href="/css/styleCreateNovels.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css" rel="stylesheet" />

<main>
    <section>
       
        <form asp-action="CreateNovels" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="form_item">
                    <div class="form_item_header">
                        <div class="header">
                            <b> Title</b>
                        </div>
                    </div>
                    <div class="item_info">
                        <input class="input is-rounded" type="text" asp-for="Title" maxlength="100" placeholder="Enter your title" style="height:62px;padding:12px">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form_item">
                    <div class="form_item_header">
                        <div class="header">
                            <b> Description</b>
                        </div>
                    </div>
                    <div class="item_info">

                        <textarea rows="10" type="text" maxlength="1000" asp-for="Description" placeholder="Enter your descripton" style="width:100%;border-radius:12px;padding:12px"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form_group_thumbnail">
                <div class="form_item_header">
                    <div class="header">
                        <b> Thumbnail</b>
                    </div>
                </div>

                <div class="item_info_thumbnail">

                    <div class="form_thumbnail">
                        <input id="img_load" asp-for="Thumbnail" class="input_thumbnail" type="file" multiple onchange="loadFileThumbnail(event)">
                        <img id="img-recent" src="https://cdn.discordapp.com/attachments/751417489262641226/866892583992688670/clouduploadfilestorageuploadicon-1320190558968694328.png" alt="" />
                        <span asp-validation-for="Thumbnail" class="text-danger"style="margin-left: -32px;"></span>
                        @*<label class="btn_upload" for="img_load">
            Upload
        </label>*@
                    </div>

                </div>
            </div>

            <div class="form_group_bookcover">
                <div class="form_item_header">
                    <div class="header">
                        <b> Bookcover</b>
                    </div>
                </div>
                <div class="imgBookcover">
                    <img src="https://d30womf5coomej.cloudfront.net/resources/images/some/tapamon-bookcover.png" alt="book-cover" width="396">
                </div>

                <div class="item_info_bookcover">

                    <div class="form_bookcover">
                        <input id="img_loadbookcover" asp-for="Bookcover" class="input_bookcover" type="file" multiple onchange="loadFilebookCover(event)">
                        <img id="img-bookcover-recent" src="https://cdn.discordapp.com/attachments/751417489262641226/866892583992688670/clouduploadfilestorageuploadicon-1320190558968694328.png" alt="" />
                        <span asp-validation-for="Bookcover" class="text-danger"style="margin-left: 50px;"></span>
                        @*<label class="btn_upload_bookcover" for="img_loadbookcover">
            Upload
        </label>*@

                    </div>
                </div>
            </div>


            <div class="form_group_banner">
                <div class="form_item_header">
                    <div class="header">
                        <b> Banner</b>
                    </div>
                </div>
                <div class="item_info_banner">

                    <div class="form_banner">
                        <input id="img_loadbanner" asp-for="Banner" class="input_banner" type="file" multiple onchange="loadFilebookBanner(event)">
                        <img id="img-banner-recent" src="https://cdn.discordapp.com/attachments/751417489262641226/866892583992688670/clouduploadfilestorageuploadicon-1320190558968694328.png" style="width: 150px; height: 122px; margin-left: 138px; margin-top: 31px; margin-bottom: 54px; " alt="" />
                        <span asp-validation-for="Banner" class="text-danger"style="margin-left: 131px;"></span>
                        @*<label class="btn_upload_banner" for="img_loadbanner">
            Upload
        </label>*@
                    </div>
                </div>
            </div>

            <div class="form_checkboxList" style="margin-top: 260px;">
                <div class="form_item_checkbox">
                    <b> Genres </b>
                </div>
                <div class="checkbox" style="margin-top: 23px; margin-left: 85px ">
                    @for (int i = 0; i < Model.genres.Count; i++)
                    {
                        <input type="hidden" asp-for="@Model.genres[i].Value" />
                        <input type="hidden" asp-for="@Model.genres[i].Text" />
                        <input asp-for="genres[i].Selected" /> @Model.genres[i].Text

                    }
                </div>
                <div class="btn_submit" style="margin-left: 179px; margin-top: 35px; ">
                    <input type="submit" value="Save" class="btn btn-primary" style="width: 244px; " />
                </div>
            </div>

        </form>
    </section>
</main>
<script>
 
    var loadFileThumbnail = function (event) {
        var output = document.getElementById('img-recent');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    };
    var loadFilebookCover = function (event) {
        var output = document.getElementById('img-bookcover-recent');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    };
    var loadFilebookBanner = function (event) {
        var output = document.getElementById('img-banner-recent');
        output.style.height = "100%";
        output.style.width = "100%";
        output.style.margin = "0";
        output.style.marginBottom = "12px";
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    };
</script>

webtruyentranh/Views/Novel/Getnovels.cshtml
@model IEnumerable<Genre>;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layoutpage";
}
<link href="~/css/Style-novels.css" rel="stylesheet" />
<main role="main" class="pb-3" style="margin-top: 50px; ">

    <section class="ftco-section">

        <!-- Main container -->
        <nav class="level">

            <div class="level-left">
                <div class="level-item">
                    <div> </div>
                    <ul class="ge-ul">
                        <li class="ge-li ge-li-click" id="0">All Genres</li>
                        @foreach (var item in Model)
                        {
                            <li class="ge-li" id="@item.Id" >@item.GenreName</li>

                        }
                    </ul>
                </div>
            </div>

        </nav>
        <hr />
        <nav class="level">
            <div class="level-left">
                <div class="level-item">
                    <div> </div>
                    <ul class="ge-ul">
                        <li class="q-li q-li-click" id="POPULAR">Popular</li>
                        <li class="q-li" id="FRESH">Fresh</li>
                        <li class="q-li" id="ALL">ALL</li>
                    
                    </ul>
                </div>
            </div>
        </nav>
        <hr />
        <div class="request-content">
            <div class="columns request-containner now-pagination" id="1">
                <div class="column is-6">
                    <p style="margin:15px 0 15px 0;" id="count-result"></p>
                    <ul id="data-novels">


                        @*<li>
                            <a class="columns">
                                <div class="column is-3 ">

                                    <div class="image-flash item_wrap">
                                        <figure><img style="border-radius:5px;" src="" /></figure>

                                    </div>
                                </div>
                                <div class="column is-6 item_detail">
                                    <p class="item_title">

                                    </p>

                                    <p class="item_info">
                                        <span class="G-item">

                                        </span>
                                        <span class="G-item cachder">|</span>

                                    </p>

                                </div>
                            </a>
                        </li>*@


                    </ul>
                </div>
                <div class="column">
                    <div class="block" id="ft-container" style="position:fixed;">
                        <p class="ft-title" style="font-size:26px;">Featured novels</p>    
                       
                    </div>
                </div>
            </div>
        </div>       
    </section>
</main>
<script src="~/js/jquery-3.2.1.min.js"></script>
<script>
    var Floaddata = function (elm, q, pagination, firstloaddata) {
 
        const search_data_string = new URLSearchParams(window.location.search);
        const searchdata = search_data_string.get('search'); 
             $.ajax({
                 type: "GET",
             url: "@Url.Action("RequestItems", "Novel")",
             data: {
               'ge': elm,
                 'q': q,
                 'pagination': pagination,
                 'search': searchdata
                },
                dataType: "json",
             success: function (data) {
                 var result = JSON.parse(data);
                 if (firstloaddata) {
                     $('#count-result').text(result['countresult'] + ' results');
                 }
               $(result['Novels']).each(function (idx, nl) {
                   var genre = "";
                   $(nl.Genres).each(function (idx, ge) {
                       genre = genre + " " + ge.GenreName;
                   });
                   $('#data-novels').append(
                       '<li>' +
                       '<a class="columns" href="/novel/' + nl.Slugify + '/episode/1' +'" style="color:black;" >' +
                       '<div class="column is-3 ">' +

                       '  <div class="image-flash item_wrap">' +
                       '<figure><img style="border-radius:5px; height:220px; width:150px;"src=' + nl.BookCover + '></figure>' +

                       '</div>' +
                       '</div>' +
                       '<div class="column is-6 item_detail">' +
                       '  <p class="item_title">' + nl.Title +

                       ' </p>' +

                       ' <p class="item_info">' +
                       ' <span class="G-item">' +

                       '  </span>' +
                       '<span class="G-item cachder">' + genre + " " + '| ' + nl.LikeCount +' likes' + '</span>' +

                       '   </p>'+

                       ' </div>'+
                       ' </a>'+
                     '  </li>'
                   );
               });
                 $('.item-contaniner').remove();
               
               $(result['Featurednovel']).each(function (idx, ft) {
                   $('#ft-container').append(
                       '<a  href="/novel/' + ft.Slugify + '/episode/1' + '" style="color:black;" >'+
                       ' <div class="item-contaniner" style="display:flex; margin : 10px 0px 10px 0px;">'+

                       '<div class="block" style="width:80px; height:120px;">'+
                       ' <img style="width:100%;height:100%;" src=' + ft.BookCover +' />'+
                       ' </div>' +
                       '    <div class="block" style="width:60%; margin-left:10px;">'+
                       '  <p class="item_title">' + ft.Title+' </p>'+
                       '   </div>'+

                       '   </div>'+
                       '   </a>'

                   );
               });

            }
      });

    }
    $('.ge-li').click(function () {
        $('.ge-li').removeClass('ge-li-click');

        $(this).addClass('ge-li-click');

        loadcontent();
                            });
    $('.q-li').click(function () {
        $('.q-li').removeClass('q-li-click');

        $(this).addClass('q-li-click');
        loadcontent();
                            });
    var loadcontent = function () {
        $('.now-pagination').attr("id", 1);
        var pagination = $('.now-pagination').attr("id");
        var elm = $('.ge-li-click').attr("id");
        var q = $('.q-li-click').attr("id");
       
        $('#data-novels').empty();
       
        Floaddata(elm, q, pagination, firstloaddata =true);
          $(window).on("scroll", function() { // EVENT lang xuong bot
                var docHeight = $(document).height();
              var winScrolled = $(window).height() + $(window).scrollTop();
              var abc = docHeight - winScrolled; 
              if ((docHeight - winScrolled) < 1 && (docHeight - winScrolled) != 0) {               
               $('.now-pagination').attr("id", Number(pagination) + 1);
                  pagination = $('.now-pagination').attr("id");    
                  Floaddata(elm, q, pagination, firstloaddata = false);
              }            
       });
    }

    $(document).ready(loadcontent);
</script>

webtruyentranh/Views/Novel/UpdateNovel.cshtml
@model UploadImage_Viewmodel
@{
    ViewData["Title"] = "UpdateNovel";
    Layout = "~/Views/Shared/_Layoutpage.cshtml";
}

<link href="/css/styleCreateNovels.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css" rel="stylesheet" />

<main>
    <section>

        <form method="post" asp-action="UpdateNovel" asp-controller="Novel" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="form_item">
                    <div class="form_item_header">
                        <div class="header">
                            <b> Title</b>
                        </div>
                    </div>
                    <div class="item_info">
                        <input class="input is-rounded" type="text" asp-for="Title" maxlength="100" placeholder="@Model.Title" style="height:62px;padding:12px">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form_item">
                    <div class="form_item_header">
                        <div class="header">
                            <b> Description</b>
                        </div>
                    </div>
                    <div class="item_info">

                        <textarea rows="10" type="text" maxlength="1000" asp-for="Description" placeholder="@Model.Description" style="width:100%;border-radius:12px;padding:12px"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form_group_thumbnail">
                <div class="form_item_header">
                    <div class="header">
                        <b> Thumbnail</b>
                    </div>
                </div>

                <div class="item_info_thumbnail">

                    <div class="form_thumbnail">
                        <input id="img_load" asp-for="Thumbnail" class="input_thumbnail" type="file" multiple onchange="loadFileThumbnail(event)">
                        <img id="img-recent" src="@ViewBag.recentThumbnail" alt="" />
                        <span asp-validation-for="Thumbnail" class="text-danger"></span>
                        @*<label class="btn_upload" for="img_load">
            Upload
        </label>*@
                    </div>

                </div>
            </div>

            <div class="form_group_bookcover">
                <div class="form_item_header">
                    <div class="header">
                        <b> Bookcover</b>
                    </div>
                </div>
                <div class="imgBookcover">
                    <img src="https://d30womf5coomej.cloudfront.net/resources/images/some/tapamon-bookcover.png" alt="book-cover" width="396">
                </div>

                <div class="item_info_bookcover">

                    <div class="form_bookcover">
                        <input id="img_loadbookcover" asp-for="Bookcover" class="input_bookcover" type="file" multiple onchange="loadFilebookCover(event)">
                        <img id="img-bookcover-recent" src="@ViewBag.recentBookcover" alt="" />
                        <span asp-validation-for="Bookcover" class="text-danger"></span>
                        @*<label class="btn_upload_bookcover" for="img_loadbookcover">
            Upload
        </label>*@

                    </div>
                </div>
            </div>


            <div class="form_group_banner">
                <div class="form_item_header">
                    <div class="header">
                        <b> Banner</b>
                    </div>
                </div>
                <div class="item_info_banner">

                    <div class="form_banner">
                        <input id="img_loadbanner" asp-for="Banner" class="input_banner" type="file" multiple onchange="loadFilebookBanner(event)">
                        <img id="img-banner-recent" src="@ViewBag.recentBanner" style="width: 100%; height: 100%; margin-bottom: 10px; " alt="" />
                        <span asp-validation-for="Banner" class="text-danger"></span>
                        @*<label class="btn_upload_banner" for="img_loadbanner">
            Upload
        </label>*@
                    </div>
                </div>
            </div>

            <div class="form_checkboxList" style="margin-top: 260px;">
                <div class="form_item_checkbox">
                    <b> Genres </b>
                </div>
                <div class="checkbox" style="margin-top: 23px; margin-left: 145px; max-width: 330px ">

                    @for (int i = 0; i < Model.genres.Count; i++)
                    {
                        
                        <input type="hidden" asp-for="@Model.genres[i].Value" />
                        <input type="hidden" asp-for="@Model.genres[i].Text" />
                        <input asp-for="genres[i].Selected" /> @Model.genres[i].Text

                    }
                </div>
                <div class="btn_submit" style="margin-left: 179px; margin-top: 24px; ">
                    <input type="submit" value="Save" class="btn btn-primary" style="width: 244px; " />
                </div>
            </div>

        </form>
    </section>
</main>
<script>

    var loadFileThumbnail = function (event) {
        var output = document.getElementById('img-recent');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    };
    var loadFilebookCover = function (event) {
        var output = document.getElementById('img-bookcover-recent');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    };
    var loadFilebookBanner = function (event) {
        var output = document.getElementById('img-banner-recent');
        output.style.height = "100%";
        output.style.width = "100%";
        output.style.margin = "0";
        output.style.marginBottom = "12px";
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function () {
            URL.revokeObjectURL(output.src)
        }
    };

</script>