webtruyentranh/Controllers/EpisodeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebTruyenTranhDataAccess.Context;

using WebTruyenTranhDataAccess.Models;

using Microsoft.AspNetCore.Identity;

namespace webtruyentranh.Controllers
{
    public class EpisodeController : Controller
    {
        private readonly ComicContext _context;
        private readonly UserManager<Account> userManager;
        private readonly SignInManager<Account> signInManager;

        public EpisodeController(ComicContext context, UserManager<Account> userManager, SignInManager<Account> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _context = context;
        }

        [HttpGet]
        public IActionResult getlistepisode()
        {
            return View();
        }

        [HttpGet]
        [Route("novel/{novelSlugify}/episode/{episodenumber}")]
        public IActionResult Episode(string novelSlugify, int episodenumber)
        {
            var episode = _context.Episodes.Where(ep => ep.Novel.Slugify.Equals(novelSlugify)).Where(ep => ep.EpisodeNumber == episodenumber).FirstOrDefault();
            if (episode == null)
                return PartialView("~/Views/Shared/_notfound.cshtml");
            ViewBag.epcount = _context.Episodes.Where(ep => ep.Novel.Slugify == novelSlugify).Count();
            var novel = _context.Novels.Include(m => m.Likes).Include(m => m.Genres).FirstOrDefault(p => p.Slugify == novelSlugify);
            ViewBag.novel = novel;
            return View(episode);
        }

        [Route("novel/{novelId}/episode/Create")]
        [HttpGet]
        [Authorize]
        public IActionResult Create(long novelId)
        {
            var model = new Episode();
            model.NovelId = novelId;
            return View(model);
        }

        [Route("novel/{novelId}/episode/Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Episode model)
        {
            if (ModelState.IsValid)
            {
                var ep = new Episode();
                var lastEpisode = _context.Episodes.Where(m => m.NovelId == model.NovelId).OrderBy(p => p.EpisodeNumber).LastOrDefault();
                ep.Id = model.Id;
                ep.NovelId = model.NovelId;
                if (lastEpisode == null)
                {
                    ep.EpisodeNumber = 1;
                }
                else
                {
                    ep.EpisodeNumber = lastEpisode.EpisodeNumber + 1;
                }

                ep.Title = model.Title;
                ep.Content = model.Content;
                ep.Views = model.Views;
                

                try
                {
                    _context.Episodes.Add(ep);
                    //_context.SaveChanges();
                 
                    _context.SaveChanges();

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("save_error", "Save Error" + ex.Message);
                    return View(model);
                }
                var listuser = _context.Accounts.Where(a => a.Subscriptions.Any(s => s.Novel.Id == model.NovelId)).ToList();
       
                foreach (var user in listuser)
                {
                    _context.Notifications.Add(new Notification()
                    {
                       TargetAccountId=user.Id,
                        NewEpisodeId=ep.Id,
                        IsRead = false,
                        Content = "Hello, " + user.UserName + " New episode \n" + ep.Title,
                        CreateDate = DateTime.Now

                    });
                }
                _context.SaveChanges();
                return RedirectToAction("Sumary", "Dashboard");
            }
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Update(int id)
        {
            var ep = _context.Episodes.FirstOrDefault(m => m.Id == id);
            if (ep == null)
            {
                return RedirectToAction("Sumary", "Dashboard");
            }
            var edit = new Episode();
            edit.Id = ep.Id;
            edit.Title = ep.Title;
            edit.Content = ep.Content;
            return View(edit);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAsync(Episode model)
        {
            if (ModelState.IsValid)
            {
                var account = await userManager.GetUserAsync(User);
                var ep = _context.Episodes.Include(n => n.Novel.Account).FirstOrDefault(m => m.Id == model.Id && m.Novel.Account == account);

                if (ep != null)
                {
                    //ep.Id = model.Id;
                    ep.Title = model.Title;
                    ep.Content = model.Content;

                    // dua episode vao db
                    _context.Episodes.Attach(ep);
                    _context.Entry(ep).State = EntityState.Modified;

                    _context.SaveChanges();
                }
                return RedirectToAction("Sumary", "Dashboard");
            }
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int id)
        {
            var ep = _context.Episodes.FirstOrDefault(m => m.Id == id);
            if (ep == null)
            {
                return Json(new { success = false, msg = "Cannot Delete!" });
            }
            _context.Episodes.Remove(ep);
            _context.SaveChanges();
            return Json(new { success = true, msg = "" });
        }

        [HttpPost]
        public JsonResult GetEpisodes(int id)
        {
            var novel = _context.Novels.Include(n => n.Episodes).FirstOrDefault(n => n.Id == id);
            var SerialList = new List<Episode>();
            novel.Episodes.ForEach(e => SerialList.Add(new Episode()
            {
                Id = e.Id,
                EpisodeNumber = e.EpisodeNumber,
                Comments = e.Comments,
                Content = e.Content,
                Notifications = e.Notifications,
                Novel = e.Novel,
                Views = e.Views,
                Title = e.Title
            }));
            return Json(JsonConvert.SerializeObject(SerialList, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                PreserveReferencesHandling = PreserveReferencesHandling.Arrays,
                Formatting = Formatting.Indented
            }));
        }

        /**-----------------------------------------------------comment-------------------------------------------------------------**/

        public JsonResult GetComments(long Id, int pagination)
        {
            var staticnum = pagination * 5;
            var listcmt = _context.Comments.Include(c => c.ChildComments).ThenInclude(child => child.Account.Profile).Include(c => c.Account.Profile).Where(c => c.EpisodeId == Id)
                .OrderByDescending(d => d.CommentDate).Skip(staticnum - 5).Take(5).ToList();
            return Json(JsonConvert.SerializeObject(new { listcmt = listcmt }, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                Formatting = Formatting.Indented
            }));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Postcomment(long Id, string comment, string ReturnUrl)
        {
            try
            {
                var account = await userManager.GetUserAsync(User);
                _context.Comments.Attach(new Comment()
                {
                    Account = account,
                    CommentDate = DateTime.Now,
                    Content = comment,
                    EpisodeId = Id
                });
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Sorry, can't add comment");
            }
            return Redirect(ReturnUrl);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReplyComment(long Id, String Content, String ReturnUrl) //post reply and return

        { //get form reply for the mss
            Comment cmt = _context.Comments.Where(cmt => cmt.Id == Id).FirstOrDefault();
            if (cmt == null)
            {
                return PartialView("~/Views/Shared/_notfound.cshtml");
            }
            var account = await userManager.GetUserAsync(User);
            _context.ChildComments.Attach(new ChildComment { Account = account, Content = Content, CommentDate = DateTime.Now, Comment = cmt });
            _context.SaveChanges();
            return Redirect(ReturnUrl);
        }

        [HttpGet]
        public JsonResult GetEpisodes(int id, int pagination)
        {
            var novel = _context.Novels.Include(n => n.Episodes).FirstOrDefault(n => n.Id == id);
            var SerialList = new List<Episode>();
            novel.Episodes.Skip(pagination * 5 - 5).Take(5).ToList().ForEach(e => SerialList.Add(new Episode()
            {
                Id = e.Id,
                EpisodeNumber = e.EpisodeNumber,
                Comments = e.Comments,
                Content = e.Content,
                Notifications = e.Notifications,
                Novel = e.Novel,
                Views = e.Views,
                Title = e.Title
            }));

webtruyentranh/Views/Shared/_Notfound.cshtml
<link rel="stylesheet" href="~/css/notfoundcs.css">
<div id="clouds">
    <div class="cloud x1"></div>
    <div class="cloud x1_5"></div>
    <div class="cloud x2"></div>
    <div class="cloud x3"></div>
    <div class="cloud x4"></div>
    <div class="cloud x5"></div>
</div>
<div class='c'>
    <div class='_404'>404</div>
    <hr>
    <div class='_1'>THE PAGE</div>
    <div class='_2'>WAS NOT FOUND</div>
    <a class='btn' href='@Url.Action("Index","Home")'>Back to home</a>
</div>

webtruyentranh/Views/Shared/_dashboardEp.cshtml
@model IEnumerable<Novel>

<nav class="level" style="margin-top:100px">
    <div class="level-left">
        <div class="control has-icons-left">
            <div class="select" id="mySelect">
                <select>
                    @foreach (var item in Model)
                    {
                        <option value="@item.Id">@item.Title</option>
                    }
                </select>
            </div>
            <span class="icon is-medium is-left">
                <i class="fas fa-globe"></i>
            </span>
        </div>
    </div>

    <div class="level-right is-flex-direction-row">

        <div class="level-item ">

            <a href="/novel/createnovels" class="button is-primary newSeriesbtn">

                <span class="icon">
                    <i class="fa fa-book" aria-hidden="true"></i>
                </span>
                <span>New series</span>
            </a>



            <a  class="button is-primary addEpisodebtn">
                <span class="icon">
                    <i class="fas fa-plus" aria-hidden="true"></i>
                </span>
                <span href="@Url.Action("Create","Episode",new { })">Add Episode</span>
            </a>
        </div>
    </div>
</nav>
<table class="table is-striped">
    <thead>
        <tr>
            <th><abbr title="Episode">Episode</abbr></th>
            <th><abbr title="info">Thumbnail / Episode info</abbr></th>
            <th><abbr title="Status">Status</abbr></th>
            <th><abbr title="Actions">Actions</abbr></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<script type="text/javascript">
    var loadData = function (id, pagination) {
        $.ajax({
            url: '@Url.Action("GetEpisodes", "Episode")',
            data: { 'id': id, 'pagination': pagination },
            dataType: "json",
            method: 'get',
            success: function (response) {
                var result = JSON.parse(response);
                var thumbnail = result["thumbnail"];
                var slug = result["episodes"][0]["Novel"]["Slugify"];
                console.log(result);
                var table = $("table tbody");
                if (result["episodes"].length != 0) {
                    reachEnd = false;
                    isdash = true;
                }
                else {
                    reachEnd = true;
                    isdash = false;
                }

                $(result["episodes"]).each(function (idx, value) {



                    table.append('<tr class="episode-info">' +
                        '<th style="width:50px"><p>' + value["EpisodeNumber"] + '</p></th>' +
                        '<td>'
                        + '<div class= "columns is-mobile .is-variable  is-4-tablet is-4-mobile ">' +
                        '<div class="column is-one-fifth">'
                        + '<div style = "width:50px;height:50px;margin-left: 30px;">'
                        + '<img src=' + thumbnail + ' alt="testNovel">'
                        + '</div>' +
                        '</div>'

                        + '<div class="column">'
                        + '<div >'
                        + '<a href="/novel/' + slug + '/episode/' + value["EpisodeNumber"] + '" style="    color: #000000; cursor: pointer;text - decoration: none;font - weight: 700;">' + value["Title"] + '</a>'
                        + '</div>'
                        + '</div>'
                        + '<div class="column"></div>' +
                        '</div>' +
                        '</td>'
                        + '<td>' + '</td>' // status here
                        + '<td>'
                        + '<div class="buttons are-small">'
                        + '<a class="button is-primary actionBtn-update" href="/Episode/Update/?id=' + value["Id"] + '">Edit</a>'
                        + '<a class="button is-danger actionBtn-delete" data-id="' + value["Id"] + '"><i class="far fa-trash-alt fa-2x"></i></a>'
                        + '</div>'
                        + '</td >'
                        + '</tr>');
                });
                 $('.actionBtn-delete').click(function () {
                        var button = $(this); //lay doi tuong la nut dang bam
                        var id = button.attr('data-id');
                        var tr = button.closest('.episode-info') //tim cai gan nhat voi no: closest
                        if (confirm("Episode will be deleted immediately and you can't undo this action. Are you sure you want to delete this?"))
                        {
                            $.ajax({
                                url: '@Url.Action("Delete", "Episode")',
                                data: { 'id': id },
                                type: "post",
                                success: function (reponse) {
                                    tr.remove();
                                }
                            });
         }

                    });

            }
        });

    }

    //$(document).ready(function () {
    //    $('select').trigger("change");
    //});
    var pagination;
    var isFirstLoadData;
        var reachEnd = false;
    isdash = false;
    $('select').change(function () {
        var novelId = $(this).val();
        var link = "/novel/" + novelId + "/Episode/Create";
        $(".addEpisodebtn").attr("href", link);
        isFirstLoadData = true;
        pagination = 1;
        if (isFirstLoadData && pagination == 1) {
            $("table tbody").empty();
            loadData($(this).val(), pagination++);
            isFirstLoadData = false;
            isdash = true;
        }

    });

        $(window).on("scroll", function () { // EVENT lang xuong bot
            var docHeight = $(document).height();
                console.log("aa");
            var winScrolled = $(window).height() + $(window).scrollTop();
            if ((docHeight - winScrolled) < 1 && (docHeight - winScrolled) != 0 && !reachEnd && isdash) {
                reachEnd = true;
                isdash = false;
                loadData($('select option:checked').val(),pagination++)
            }
        });

</script>

webtruyentranh/Views/Shared/_novel.cshtml
@model Novel

@using Newtonsoft.Json

<section class="box columns " id="Information" style="margin-bottom: 1.5rem">
    <div class="column is-one-fifth is-relative" style="height: 220px; width: 120px; margin-right: 15px">
        <img class="thumb-overlay" src=@Model.BookCover asp-append-version="true">
    </div>
    <div class="column">
        <div class="columns">
            <div class="column is-relative">
                <span class="tag is-success ">On-going</span>
            </div>
            <div class="column"></div>
            <div class="column is-two-fifths-widescreen is-half-tablet">
                <a href="/novel/updatenovel/@Model.Id"class="button  btn-label">Edit series</a>

                <a data-novel-id="@Model.Id" class="button is-primary toEpisode">

                    <i class="fas fa-bars is-white"></i>
                </a>
                <a href="/novel/@Model.Id/Episode/Create" class="button is-primary">
                    <i class="fas fa-plus is-white"></i>
                </a>
                <a href="/Novel/Delete/@Model.Id" class="button is-primary">
                    <i class="far fa-trash-alt is-white"></i>
                </a>
            </div>
        </div>
        <div class="columns" id="info">
            <div class="column">
                <div class="columns">
                    <div class="column index__title">
                        <p>@Model.Title</p>
                    </div>
                </div>
                <div class="columns">
                    <div class="column" style="padding: 0.4rem">
                        <div>
                            <p class="index__body">
                                <span> </span>
                                Subscribers:  <span>@Model.Subscriptions.Count()</span>
                                <span><i class="fas fa-grip-lines-vertical"></i></span>
                                <span>Total word counts:<span>@Model.totalWordCount()</span></span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column decrese-padding">
                <div class="columns">
                    <div class="column cell__key">Episodes</div>
                    <div class="column cell__value">@Model.Episodes.Count()</div>
                    <div class="column cell__key">Type</div>
                    <div class="column cell__value">@Model.getType()</div>
                    <div class="column cell__key">Updated</div>
                    <div class="column cell__value">@Html.FormatValue(Model.LastestUpdate, "{0:dd-MMM-yyyy}")</div>
                </div>
                <div class="columns">
                    <div class="column cell__key">Views</div>
                    <div class="column cell__value">@Model.Episodes.Sum(e => e.Views)</div>
                    <div class="column cell__key">Likes</div>
                    <div class="column cell__value">@Model.LikeCount</div>
                    <div class="column cell__key">Subscribers</div>
                    <div class="column cell__value">@Model.Subscriptions.Count()</div>
                </div>
            </div>
        </div>
    </div>
</section>

webtruyentranh/Views/Shared/_summary.cshtml
@model IEnumerable<Novel>

<section class="block" style="margin-top: 50px">
    <h1 class="block index-label">
        Sumary
    </h1>
    <nav class="level">
        <div class="level-item has-text-centered Sumary " style="margin-right: 10px">
            <div>
                <p class="heading">Total Likes</p>
                <p class="title">@ViewBag.TotalLikes</p>
            </div>
        </div>
        <div class="level-item has-text-centered Sumary" style="margin-right: 10px">
            <div>
                <p class="heading">Total Views</p>
                <p class="title">@ViewBag.TotalViews</p>
            </div>
        </div>
        <div class="level-item has-text-centered Sumary " style="margin-right: 10px">
            <div>
                <p class="heading">Total Comments</p>
                <p class="title">@ViewBag.TotalTotalComments</p>
            </div>
        </div>
    </nav>
</section>
<section class="block">

    <div class="columns">
        <h1 class=" column is-2 block index-label ">
            Series(@Model.Count())
        </h1>
        <div class="column is-2 is-offset-4 is-narrow">
            <a href="/novel/createnovels" class="button is-primary btn-label newSeries">
                <span class="icon">
                    <i class="fa fa-book"></i>
                </span>
                <span>New series</span>
            </a>
        </div>
    </div>
    <div class="columns is-desktop">
        <div class="column is-three-quarters-widescreen  is-full-tablet">
            @foreach (var novel in Model)
            {
                <partial name="_novel" model="novel" />
            }
        </div>
    </div>
</section>
<script>
     $(document).ready(function () {
        $(".toEpisode").on("click", function () {
            var id = $(this).attr("data-novel-id");

            $.ajax({
                type: "POST",
                url: "@(Url.Action("GetEpDashboard", "Dashboard"))",
                success: function (data) {
                    $(".dashboard").html('');
                    $(".dashboard").html(data);
                    if (id != undefined) {
                        $("select").val(id).trigger("change");
                    }
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve Episodes.');
                }
            });
        });
    });
</script> 